name: Deploy package to Nuget

on: 
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build
      run: dotnet build --configuration Release
    - name: Unit Tests
      run: dotnet test
    - name: Build NuGet Package
      run: dotnet pack ./src/BlazorFly.Grpc/BlazorFly.Grpc.csproj --configuration Release --output NuGetPackages
    - name: Deploy NuGet Package
      run: dotnet nuget push ./NuGetPackages/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --no-symbols true
